# logo
logo = "images/logo.png"

# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "140px"
logo_height = "40px"

# if logo_webp set false, it will not generate WEBP version of logo
logo_webp = true # default is true

# logo text will only show when logo is missing.
logo_text = "twango.dev"

favicon = "images/favicon.png"

twitter = "@twangodev"

[metadata]
keywords = ["James Ding", "twango", "twangodev", "twango.dev", "twango dev"]
description = "James Ding's personal portfolio website."
author = "James Ding"
image = "images/favicon.png" # this image will be used as fallback if a page has no image of its own