######################## default configuration ####################
baseURL = "https://twango.dev/"
title = "James Ding"
theme = "gofolium-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/Los_Angeles"
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 4 # see https://gohugo.io/content-management/excerpts/
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = ["fr"] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage


############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 99
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"

# JS Plugins
[[params.plugins.js]]
link = "https://kit.fontawesome.com/19d90086cc.js"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/particles/particles.min.js"
[[params.plugins.js]]
link = "plugins/particles/stats.min.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
[[params.plugins.js]]
link = "js/gallery-slider.js"
[[params.plugins.js]]
link = "plugins/youtube-lite.js"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "home"
URL = "home"
weight = 1

[[menu.main]]
name = "about"
URL = "about"
weight = 2

#[[menu.main]]
#name = "publication"
#URL = "publication"
#weight = 3
#
#[[menu.main]]
#name = "talk"
#URL = "talk"
#weight = 4
#
[[menu.main]]
name = "projects"
URL = "projects"
weight = 5
#
#[[menu.main]]
#name = "blog"
#URL = "blog"
#weight = 6
#
[[menu.main]]
name = "contact"
URL = "contact"
weight = 7


#################### default parameters ################################
[params]
# Meta data
author = "James Ding"
description = """
sleep deprived cs major from the bay @ uw-madison. 

i build shit. obsessed with tech, caffeine, and figuring out how to make life suck less through any form of engineering.

when i'm not coding, i enjoy biking, messing with electronics, 3d printing stuff, and allegedly touching grass. i occasionaly play video games.
"""

# body particles
particles = true

# Preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

# Navigation button
[params.navigation_button]
enable = true
label = "Résumé"
link = "https://flowcv.com/resume/soqdnfsvwo"
  
############################# social site ########################
# Icon Reference: https://themify.me/themify-icons

[[params.social]]
title = "facebook"
icon = "ti-facebook"
link = "https://www.facebook.com/dingjems"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt"
link = "https://twitter.com/twangodev"

[[params.social]]
title = "instagram"
icon = "ti-instagram"
link = "https://www.instagram.com/dingjems/"

[[params.social]]
title = "github"
icon = "fa-brands fa-github"
link = "https://github.com/twangodev"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/jamesding365/"

[[params.social]]
title = "orcid"
icon = "fa-brands fa-orcid"
link = "https://orcid.org/0009-0008-4980-8437"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

########################### Imports ################################

[[imports]]
path = "github.com/gethugothemes/hugo-modules/images"